# Generated by Django 4.2.23 on 2025-07-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_moodcheckin'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='coffee_recommendation',
            field=models.TextField(blank=True),
        ),
    ]
