# Generated by Django 4.2.23 on 2025-07-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_mood_coffee_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='affirmational_roast',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mood',
            name='spotify_track_link',
            field=models.URLField(blank=True),
        ),
    ]
